name: darttrack
description: Application to watch files changes and restart dart application
version: 1.2.1
homepage: https://paveltretyakovru.github.io/darttrack/
repository: https://github.com/paveltretyakovru/darttrack

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  darttrack: darttrack
dependencies:
  argenius: ^1.0.0
